# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/backend/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: Install latest version of .NET Core (2.2.6)
  inputs:
    version: '2.2.301'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: '**/src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: '**/src/**/*.csproj'

- script: |
    dotnet publish ./src/DuplicateFinder --configuration "Release" --output bin/Release/publish
- script: |
    cd ./src/DuplicateFinder
    docker build -t djohnnie/duplicatefinder .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/duplicatefinder